name: Check for New Releases & Build

on:
  schedule:
    - cron:  '30 5,17 * * *'
  push:
    branches:
      - '*'

jobs:
  check-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script for updates
        run: python check_releases.py

      - name: Prepeare package
        run: |
          chmod +x packagebuild.sh
          ./packagebuild.sh
          
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: release-${{ github.sha }}
          release_name: Release ${{ github.sha }}
          body: |
            This is an automated release, and description of new changes isn't available for now.
            --
            
            What to choose ?
            
            SD_Out.zip : SD content without homebrews (bare minimum)
            SD_Out_Tools.zip : SD content with homebrews
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload SD Out Without Tools
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: SD.zip
          asset_name: SD_Out.zip
          asset_content_type: file/zip
          
      - name: Upload SD Out With Tools
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: SD_T.zip
          asset_name: SD_Out_Tools.zip
          asset_content_type: file/zip

      - name: Upload zip files as assets
        uses: actions/upload-artifact@v2
        with:
          name: release-assets
          path: output.zip
